name: grand_edu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  flutter_math_fork: ^0.7.1
  equatable: ^2.0.5
  lottie: ^2.6.0
  flashy_tab_bar2: ^0.0.6
  mask_text_input_formatter: ^2.5.0
  percent_indicator: ^4.2.3
  faker: ^2.1.0
  vibration: ^1.8.1
  page_transition: ^2.0.9
  anim_search_bar: ^2.0.3
  intl: ^0.18.1
  syncfusion_flutter_charts: ^22.2.9
  google_fonts: ^5.1.0
  flutter_zoom_drawer: ^3.1.1
  pluto_grid: ^7.0.2
  carousel_slider: ^4.2.1
  flutter_tex: ^4.0.3+4
  glassmorphism_widgets: ^0.2.2
  rounded_loading_button: ^2.1.0
  youtube_player_flutter: ^8.1.2
  fl_chart: ^0.63.0
  flutter_rating_bar: ^4.0.1

  #firebase
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/

    - lib/data/1/
    - lib/data/2/
    - lib/data/3/
    - lib/data/4/
    - lib/data/5/
    - lib/data/6/
    - lib/data/7/
    - lib/data/8/
    - lib/data/9/

  fonts:
    - family: Numbers
      fonts:
        - asset: assets/fonts/clementnumbers-regular.otf
