import 'package:grand_edu/utils/def.dart';

import '../titles.dart';

Map<String, String> uz = {
  t.home: "Asosiy",
  t.saved: "Saqla",
  t.leaderboards: "Faol",
  t.theme: "Mavzu",
  t.profile: "Profil",
  t.unit: "Bo'lim",
  t.formula: "Formula",
  t.test: "Test",
  t.repeat: "Takrorlash",
  t.errors: "Xato",
  def.formula: "Formulalarni takrorlash",
  def.error: "Xatolar ustida ishlash",
  def.theme: "Mavzularni qaytarish",
  t.shop: "Bozor",
  t.seeAll: "BARCHASINI KO'RISH",
  t.grandEdu: "Grand edu",
  t.question: "Savol",
  t.nextLeague: "Keyingi liga",
  t.keepLeague: "Ligada qolish",
  t.previousLeague: "Avvalgi liga",
  t.x2prevLeague: "Ikkita avvalgi liga",
  t.resume: "Davom ettirish",
  t.finished: "Tamom bo'lgan!",
  t.start: "Boshlash",
  t.support: "Yordam",
  t.back: "Ortga qaytish",
  t.booking: "BAND QILISH",
  def.support:
      "Qiynalayotkan mavularingizni yordamchi ustoz tushuntirb berishini xohlasangiz, o'zingizga ma'qul vaqtda uchrachuv tashkillashtiring.",
  t.afternoon: "Abetdan keyin",
  t.morning: "Ertalab",
  t.evening: "Shomdan keyin",
  t.today: "Bugun",
  t.tomorrow: "Ertaga",
  t.dayAT: "Indinga",
  t.done: "Tamom",
  t.selectTheme: "Mavzuni tanlash",
  t.problem: "Muammo...",
  t.waiting: "Kutilmoqda",
  t.cancelled: "Bekor qilingan",
  def.reapply:
      "Band qilgan darsingiz vaqti o'tmagnucham boshqa dars band qila olmaysiz.",
  t.cancel: "Bekor qilish",
  t.video: "Video",
  t.questions: "Savollar",
  t.solve: "Yechish",
  def.memoFormula: "Formulani yodlash",
  t.memo: "Yodladim",
  t.formula2: "formula",
  def.watchYoutube: "Youtube da ko'rish",
  t.watched: "Ko'rdim",
  t.select: "Tanlang",
  t.submit: "Javobni qabul qilish",
  t.apply: "Topshirish",
  t.result: "Natija",
  t.next: "Keyingi savol",
  t.exit: "Chiqish",
  def.haveAl: "da qo'shimcha darsingiz bor, kelish esingizdan chiqmasin, iltimos!",
  t.continuee: "Davom ettirish",
  def.continueLeague: "Ligadagi misollarni yechishni davom ettirishingiz kerak.",
  t.progress: "Progres",
  t.feedback: "Fikr",
  def.feedback: "Qo'shimcha dars haqida fikringizni yozib qoldiring, iltimos.",
  t.save: "Saqlash",
};
